### PR TITLE
Fix SimpleIndexer fit method to set inputCol and outputCol correctly

### LINKED ISSUE #89: Failed to find a default value for inputCol
There seems to be a problem with https://github.com/high-performance-spark/high-performance-spark-examples/blob/master/src/main/scala/com/high-performance-spark-examples/ml/CustomPipeline.scala#L125. For example, if we try testing it thus
```scala
    val indexer = new SimpleIndexer()
    indexer.setInputCol("inputColumn")
    indexer.setOutputCol("categoryIndex")
    val model = indexer.fit(ds)
    val predicted = model.transform(ds)
```
the `indexer` has the inputCol set, but the `model` (that is, object that's returned by `indexer.fit`) does not. So when we try `model.transform`, it complains that it "Failed to find a default value for inputCol". 

Following https://stackoverflow.com/questions/40847625/spark-custom-estimator-access-to-paramt, @conorbmurphy and I were able to "solve" the problem by hard coding the column names within the class with

    setDefault(inputCol, "inputColumn")
    setDefault(outputCol, "categoryIndex")

but that's hardly the right solution. What _should_ happen is the paramMap should be copied into the `SimpleIndexerModel` when it's generated in the `fit` method, but we can't figure out how to do that since `paramMap` is protected.

### PR DESCRIPTION
**Pull request by MadDataScience**
This fixes #89. What was happening before is that after SimpleIndexer was fit to a dataframe, the inputCol and outputCol params were not carrying through to the new object. This change fixes that. I also added a couple tests.

Credit to @conorbmurphy for finding this bug and helping me figure it out.

### CODE REVIEW

File: src/main/scala/com/high-performance-spark-examples/ml/CustomPipeline.scala [hunk 1]
```diff
@@ -122,7 +122,10 @@ class SimpleIndexer(override val uid: String)
     import dataset.sparkSession.implicits._
     val words = dataset.select(dataset($(inputCol)).as[String]).distinct
       .collect()
-    new SimpleIndexerModel(uid, words)
+    val model = new SimpleIndexerModel(uid, words)
+    model.set(inputCol, $(inputCol))
```
Comment (holdenk) [inline src/main/scala/com/high-performance-spark-examples/ml/CustomPipeline.scala]: Thanks for catching this! The proper fix is likely to use the `copyValues` function from the Params trait.

**Comment by holdenk** [comment]
Thanks for catching this, and especially thanks for adding a test. I think we can probably use the `copyValues` function and it might be a bit clearer (and easier to handle for people's own custom models with more parameters).

File: src/main/scala/com/high-performance-spark-examples/ml/CustomPipeline.scala (hunk 1 above)
Comment (MadDataScience) [inline src/main/scala/com/high-performance-spark-examples/ml/CustomPipeline.scala]: That was my first thought as well. (Actually, I tried using `copy`, not `copyValues`, but I think it would have the same problem.) Both `copy` and `copyValues` seem to need `extra` which is of type `ParamMap` but the `paramMap` property is private and `extractParamMap` just returns an empty map.

Comment (holdenk) [inline src/main/scala/com/high-performance-spark-examples/ml/CustomPipeline.scala]: So `copy` is a bit different -- in `copyValues` the `extra` is an optional paramater (it has the default value of `ParamMap.empty`. If that doesn't work let me know and we can open a JIRA to fix the API on the Spark side for that.

**Comment by VoluntasTua** [comment]
I stand corrected. `copyValues` did the trick. Unfortunately, IntelliJ puked all over my commit. I hope you don't mind I added .idea/ to .gitignore. (I didn't mean to include that in my commit, but maybe just as well.)

**Comment by MadDataScience** [comment]
I stand corrected. `copyValues` did the trick. Unfortunately IntelliJ puked all over my repo. I think I cleaned it up. I hope you don't mind I added .idea/ to .gitignore. I didn't mean to include that in my commit but it might be just as well.
